default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity : 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

  joint_2:
    has_velocity_limits: true
    max_velocity : 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

  joint_3:
    has_velocity_limits: true
    max_velocity : 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  
  joint_4:
    has_velocity_limits: true
    max_velocity : 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

  joint_5:
    has_velocity_limits: true
    max_velocity : 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0

